=== eclipse-basyx/basyx-databridge/databridge.camel-jsonata/src/main/resources/jsonatatransformer.schema.json
{
    "$id": "https://example.com/person.schema.json",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "jsonjacksontransformer.json",
    "type": "object",
    "required": [
        "uniqueId",
        "queryPath",
        "inputType",
        "outputType"
    ],
    "properties": {
        "uniqueId": {
            "title": "Unique ID",
            "type": "string",
            "description": "Unique ID to match options",
            "pattern": "^[a-z0-9-]+$"
        },
        "queryPath": {
            "title": "Query Path",
            "type": "string",
            "description": "Path to the JSONata file (relative only!)",
            "pattern": "^[a-zA-Z0-9/-\\.\\+]+$"
        },
        "inputType": {
            "title": "Input Type",
            "enum": [
                "JsonString",
                "Jackson"
            ],
            "description": "Type of the input"
        },
        "outputType": {
            "title": "Output Type",
            "enum": [
                "JsonString",
                "Jackson"
            ],
            "description": "Type of the output"
        }
    }
}

=== eclipse-basyx/basyx-databridge/databridge.examples/databridge.examples.dot-aas-v3-multicast/src/main/resources/jsonatatransformer.json
[
	{
		"uniqueId": "ProcessId",
		"queryPath": "ProcessId.jsonata",
		"inputType": "JsonString",
		"outputType": "JsonString"
	},
	{
		"uniqueId": "processResult",
		"queryPath": "processResult.jsonata",
		"inputType": "JsonString",
		"outputType": "JsonString"
	},
	{
		"uniqueId": "processData",
		"queryPath": "processData.jsonata",
		"inputType": "JsonString",
		"outputType": "JsonString"
	},
	{
		"uniqueId": "processDuration",
		"queryPath": "processDuration.jsonata",
		"inputType": "JsonString",
		"outputType": "JsonString"
	}
]
